### ISSUE TITLE
bug dust = gray concrete powder

### ISSUE THREAD

**Issue by RIPISDRAD** [Slimefun-Addon-Community/Galactifun#97] opened 2021-11-15 17:51 UTC
hey again when u place the moon dust above a two tall pillar (like no gravity issue here_exactly)
there is a duplication that make a gray concrete powder
and that was all

**Comment by Seggan** [comment] 2021-11-15 17:56
duplicate of #91

**Closed by Seggan** 2021-11-15 17:56 UTC
Labels: bug
